import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    height: "auto",
  },
  topBar: {
    backgroundColor: "hsl(0, 0%, 95%)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingBottom: 20,
    elevation: 10,
    borderBottomRightRadius: 25,
    borderColor: "black",
    borderWidth: 1,
  },
  topBar_text: {
    marginTop: 50,
    fontSize: 30,
    fontWeight: "bold",
  },
  topBar_img: {
    height: 60,
    width: 60,
    marginTop: 50,
    backgroundColor: "white",
    borderRadius: 10,
  },
  navBar: {
    width: "100%",
    height: "auto",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  navBar_tabs: {
    height: 90,
    width: 82.5,
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    backgroundColor: "hsl(0, 0%, 95%)",
    borderTopColor: "black",
    borderTopWidth: 1,
    opacity: 0.7,
  },
  navBar_tab_Add: {
    height: 90,
    width: 82.5,
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    backgroundColor: "hsl(0, 0%, 95%)",
    borderTopColor: "black",
    borderTopWidth: 1,
    transform: [{ translateY: -10 }],
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderLeftColor: "black",
    borderLeftWidth: 1,
    borderRightColor: "black",
    borderRightWidth: 1,
  },
  navBar_tabs_pressed: {
    height: 90,
    width: 82.5,
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    backgroundColor: "hsl(0, 0%, 95%)",
    borderTopColor: "black",
    borderTopWidth: 1,
    opacity: 1,
  },
  navBar_img: {
    width: 30,
    height: 30,
  },
  navBar_Add: {
    width: 20,
    height: 20,
  },
  navBar_Add_container: {
    width: 45,
    height: 45,
    backgroundColor: "hsla(129, 56%, 43%, 1)",
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  navBar_text: {
    fontSize: 11,
    color: "black",
  },
  navBar_text_pressed: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "black",
  },
  navBar_text_Add: {
    fontSize: 15,
    fontWeight: "900",
    color: "black",
  },
  contentContainer: {
    height: 791.5,
    justifyContent: "space-between",
  },
  caloriesDisplay: {
    marginTop: 20,
    backgroundColor: "#1E1E1E",
    width: "90%",
    height: 170,
    borderRadius: 15,
    alignSelf: "center",
    alignItems: "center",
    flexDirection: "column-reverse",
  },
  dateText: {
    color: "white",
    alignSelf: "flex-start",
    marginLeft: 20,
    marginBottom: 27,
  },
  caloriesBarContainer: {
    backgroundColor: "white",
    overflow: "hidden",
    width: "90%",
    height: 12,
    alignItems: "center",
    marginBottom: 15,
    borderRadius: 10,
    margin: 10,
  },
  caloriesBar: {
    height: "100%",
    alignSelf: "flex-start",
  },
  nutriDisplay_container: {
    width: "90%",
    alignSelf: "center",
    alignItems: "center",
    marginTop: 5,
    borderRadius: 15,
    flexDirection: "column",
    paddingVertical: 8,
  },
  nutriDisplay: {
    backgroundColor: "#1E1E1E",
    height: 100,
    width: 115,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  nutriDisplay_text: {
    color: "white",
    alignSelf: "center",
    marginTop: 10,
  },
  bmiContainer: {
    marginTop: 5,
    backgroundColor: "#1E1E1E",
    width: "90%",
    height: 120,
    borderRadius: 15,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  logout_button: {
    backgroundColor: "hsla(129, 56%, 43%, 1)",
    width: 160,
    height: 45,
    borderRadius: 10,
    marginTop: 15,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    marginLeft: 15,
  },
  logout_button_pressed: {
    backgroundColor: "hsla(129, 56%, 43%, 0.8)",
    width: 160,
    height: 45,
    borderRadius: 10,
    marginTop: 15,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    marginLeft: 15,
  },
  logout_button_text: {
    color: "white",
    fontSize: 20,
    fontWeight: "900",
  },
  mealContainer: {
    marginTop: 20,
    width: "90%",
    alignSelf: "center",
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  box: {
    width: "48%",
    height: 170,
    backgroundColor: "hsla(96, 56%, 35%, 1.00)",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 12,
  },
  mealBoxText: {
    backgroundColor: "black",
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  eatenButton: {
    backgroundColor: "hsla(0, 73%, 60%, 0.96)",
    padding: 8,
    textAlign: "center",
  },
  mealBoxWindow: {
    width: "90%",
    height: 600,
    backgroundColor: "hsla(96, 31%, 63%, 0.96)",
    marginBottom: 10,
    borderRadius: 5,
    justifyContent: "space-around",
    alignItems: "center",
    alignSelf: "center",
    position: "absolute",
    marginTop: "50",
    zIndex: 50,
  },
  windowContainer: {
    marginTop: "40%",
    marginHorizontal: 20,
    backgroundColor: "white",
    borderRadius: 15,
    padding: 20,
    elevation: 10,
  },

  windowTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },

  nutritionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },

  closeButton: {
    marginTop: 20,
    backgroundColor: "#ff4444",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  //Recipe
  recipesContainer: {
    margin: "auto",
    width: "95%",
  },
  AiInput: {
    height: 50,
    margin: 12,
    borderWidth: 1,
    padding: 15,
    borderRadius: 10,
  },
  recipeButton: {
    backgroundColor: "hsla(129, 56%, 43%, 1)",
    width: 160,
    height: 50,
    borderRadius: 10,
    margin: "auto",
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
  },

  //Verified
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "90%",
    alignSelf: "center",
    marginTop: 10,
  },
  card: {
    backgroundColor: "hsl(35, 54%, 35%)",
    width: "48%",
    height: 120,
    marginBottom: 13,
    borderRadius: 10,
    overflow: "hidden",
    elevation: 3
  },
  cardText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    padding: 5,
    backgroundColor: "black",
  },
  imageBackground: {
    flex: 1,
  },
  image: {
    resizeMode: "cover",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "95%",
    maxHeight: "95%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 16,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  modalContent: {
    marginBottom: 16,
  },
});
